[env:kairos_core-esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DJS_EXPR_MAX=40
lib_deps =
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson@^7
    links2004/WebSockets@^2.4.0

